name: Build and Publish Docs

on:
  workflow_dispatch:

env:
  S3_BUCKET: deliteai.dev
  CLOUDFRONT_DIST_ID: EMNMVB8Y3G0BE

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Generate dummy local.properties
        working-directory: sdks/android
        shell: bash
        run: |
          cat <<EOF > local.properties
          sdk.dir=/usr/local/lib/android/sdk
          EOF

      - name: Generate Dokka docs
        working-directory: sdks/android
        shell: bash
        run: ./gradlew dokkaGfm

      - name: Build site
        working-directory: docs
        shell: bash
        run: |
          pip install -r requirements.txt
          ./scripts/run build_website

      - name: Sync to S3
        shell: bash
        run: |
          aws s3 sync ./docs/build/deliteai.dev/html "s3://${S3_BUCKET}" --delete

      - name: Invalidate CloudFront Cache
        shell: bash
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CLOUDFRONT_DIST_ID}" \
            --paths "/*"
